sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - $(npm root)
    - ~/bin
script:
  - bundle exec image_optim --info
  - bundle exec rspec
before_install:
  - mkdir -p ~/bin
  - command -v svgo || npm install svgo
  - command -v pngout || curl -L "http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz" | tar -xz -C ~/bin --strip-components 2 --wildcards '*/x86_64/pngout'
matrix:
  include:
    - env: RAILS_VERSION='~> 3.2'
      rvm: default
    - env: RAILS_VERSION='~> 4.0' SPROCKETS_RAILS_VERSION='~> 2.0'
      rvm: '2'
    - env: RAILS_VERSION='~> 4.0'
      rvm: '2'
    - env: RAILS_VERSION='~> 5.0' SPROCKETS_RAILS_VERSION='~> 2.0'
      rvm: '2.2.2'
    - env: RAILS_VERSION='~> 5.0'
      rvm: '2.2.2'
    - env: RUBOCOP=✓
      rvm: '2.2.2'
      script: bundle exec rubocop
      before_install:
